project_id = "swbaamxtmzjnbaxizjuw"

[functions.search-artists]
verify_jwt = false

[functions.search-venues]
verify_jwt = false

[functions.backfill-venue-coordinates]
verify_jwt = true

[functions.unified-search]
verify_jwt = false

[functions.match-venue-from-location]
verify_jwt = false

[functions.get-demo-data]
verify_jwt = false

[functions.update-waitlist]
verify_jwt = false

[functions.admin-list-waitlist]
verify_jwt = false

[functions.approve-waitlist]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.resend-notification]
verify_jwt = false

[functions.parse-show-notes]
verify_jwt = false

[functions.generate-vapid-keys]
verify_jwt = false