project_id = "swbaamxtmzjnbaxizjuw"

[functions.search-artists]
verify_jwt = false

[functions.search-venues]
verify_jwt = true

[functions.backfill-venue-coordinates]
verify_jwt = true

[functions.unified-search]
verify_jwt = false